import { AIProvider, GenerateTextInput, GenerateTextResult, GenerateBlockInput, MentorReplyInput, MentorReplyResult, CoDesignerInput, CoDesignerResult } from "./provider";
import { LearningBlock } from "@/types";

export class MockAIProvider implements AIProvider {
  async generateText(input: GenerateTextInput): Promise<GenerateTextResult> {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    return {
      title: "Generated: Understanding the Basics",
      content: "This is a mock generated text explaining the core concepts. It focuses on breaking down the complexity into manageable parts, ensuring the learner grasps the foundational elements first.",
      reflectionQuestion: "How does this basic concept apply to your current work environment?"
    };
  }

  async generateStructuredBlock(input: GenerateBlockInput): Promise<Partial<LearningBlock>> {
    await new Promise(resolve => setTimeout(resolve, 1500));

    const promptPrefix = input.prompt ? `[Generated from: "${input.prompt}"]\n\n` : "";

    if (input.type === "quiz") {
      return {
        type: "quiz",
        title: "Knowledge Check",
        content: JSON.stringify({
          question: input.prompt ? `(Based on: ${input.prompt}) What is the primary difference?` : "What is the primary difference between a symptom and a root cause?",
          options: ["A symptom is visible, a root cause is hidden", "They are the same thing", "Symptoms cause root problems"],
          correctAnswer: "A symptom is visible, a root cause is hidden",
          explanation: "Symptoms are the visible manifestations of a deeper, underlying issue (the root cause)."
        }),
        learningMode: "test",
        source: "ai_assisted"
      };
    }
    
    if (input.type === "reflection") {
      return {
        type: "reflection",
        title: "Pause and Reflect",
        content: JSON.stringify({
          reflectionPrompt: input.prompt ? `Reflect on this: ${input.prompt}` : "Think of a time when you solved a problem, only for it to return later. Did you address a symptom or the root cause?",
          followUpQuestions: ["Why did it return?", "What was the actual root cause?"]
        }),
        learningMode: "reflect",
        source: "ai_assisted"
      };
    }

    if (input.type === "project_task") {
      return {
        type: "project_task",
        title: "Project Assignment: Solving the Core Friction",
        content: JSON.stringify({
          title: "Project Assignment: Solving the Core Friction",
          scenario: "Your team is running a sprint but the feedback loop from customers is completely broken. You have lots of assumptions but very few facts, leading to wasted effort and slow feature adoption.",
          task: "Design a simple lean experiment or feedback channel to gather real usage signals for a new feature. Outline who you will contact, what data you will capture, and how you will analyze it.",
          deliverable: "A 1-page Experiment Canvas or feedback collection protocol.",
          constraints: ["Timebox: 3 days to design and run the first test", "Must involve at least 5 real users", "Max 500 words for the protocol"],
          reflectionPrompt: "Reflect on how this experiment design changes your team's usual feature delivery approach."
        }),
        learningMode: "apply",
        source: "ai_assisted"
      };
    }

    if (input.type === "video") {
      return {
        type: "video",
        title: "Video Resource",
        content: "https://www.youtube.com/embed/dQw4w9WgXcQ", // Default mock video
        learningMode: "understand",
        source: "ai_assisted"
      };
    }

    if (input.type === "code") {
      return {
        type: "code",
        title: "Code Example",
        content: promptPrefix + "function example() {\n  console.log('Hello World');\n}",
        learningMode: "apply",
        source: "ai_assisted"
      };
    }

    return {
      type: "text",
      title: "AI Suggested Content",
      content: promptPrefix + "This is a fallback mock block generated by AI.",
      learningMode: "understand",
      source: "ai_assisted"
    };
  }

  async mentorReply(input: MentorReplyInput): Promise<MentorReplyResult> {
    await new Promise(resolve => setTimeout(resolve, 1000));

    const hasContext = input.moduleContext.includes("Current Active Block Context");
    let prefix = hasContext ? "[Mock AI: I see you are looking at a specific block!] " : "[Mock AI: General question] ";

    return {
      answer: prefix + "That's a very interesting point. When we focus too much on the immediate symptoms, we often miss the underlying pattern.",
      question: "Can you think of a framework or tool you've used recently that might help uncover those deeper patterns?",
      nextStep: "Try applying the '5 Whys' technique to the situation you just described."
    };
  }

  async coDesignerReply(input: CoDesignerInput): Promise<CoDesignerResult> {
    await new Promise(r => setTimeout(r, 1000));
    return {
      reply: "As a mock AI Co-Designer, I suggest adding a **Quiz Block** here to test the learner's knowledge.",
      proposedBlock: {
        type: "quiz",
        title: "Knowledge Check",
        content: JSON.stringify({
          question: "What is the main topic here?",
          options: ["Option A", "Option B", "Option C", "Option D"],
          correctAnswer: "Option A",
          explanation: "Because it is correct."
        }),
        learningMode: "test"
      }
    };
  }

  async generateCurriculum(input: { title: string; description: string }): Promise<any> {
    await new Promise(r => setTimeout(r, 1500));
    return {
      modules: [
        {
          title: "Module 1: Introduction to " + input.title,
          description: "Understanding the foundations and setting the stage.",
          learningObjectives: ["Understand core concepts of " + input.title, "Identify primary challenges"],
          blocks: [
            {
              type: "text",
              title: "What is " + input.title + "?",
              content: "This is a reading block explaining the foundations. It covers the basic tenets and explains why this topic is highly relevant today.",
              learningMode: "understand"
            },
            {
              type: "quiz",
              title: "Quick Test",
              content: JSON.stringify({
                question: "Which of the following is a primary goal of this course?",
                options: ["To master the basics", "To skip the training", "None of the above"],
                correctAnswer: "To master the basics",
                explanation: "The course is designed to build foundational mastery."
              }),
              learningMode: "test"
            }
          ]
        },
        {
          title: "Module 2: Practical Application",
          description: "Hands-on projects and tools to implement ideas.",
          learningObjectives: ["Apply frameworks", "Solve simulated conflicts"],
          blocks: [
            {
              type: "punk_game",
              title: "Rapid Execution Challenge",
              content: JSON.stringify({
                scenario: "A client calls with a major issue and needs a response within 10 minutes.",
                task: "Write a 3-step action plan to address the issue and align the team.",
                timeboxMinutes: 10,
                evaluationCriteria: ["Clarity of response", "Empathy towards client", "Feasibility of plan"]
              }),
              learningMode: "challenge"
            },
            {
              type: "reflection",
              title: "Final Reflection",
              content: JSON.stringify({
                reflectionPrompt: "How will you apply these tools in your day-to-day work environment?",
                followUpQuestions: ["What obstacle do you expect first?", "How can you mitigate it?"]
              }),
              learningMode: "reflect"
            }
          ]
        }
      ]
    };
  }

  async generateModule(input: { courseTitle: string; topic: string; description: string; existingModulesInfo?: string }): Promise<any> {
    await new Promise(r => setTimeout(r, 1500));
    return {
      title: input.topic,
      description: input.description,
      learningObjectives: ["Understand " + input.topic, "Apply standard practices of " + input.topic],
      blocks: [
        {
          type: "text",
          title: "Introduction to " + input.topic,
          content: "Welcome. This module covers " + input.topic + ". It details the core definitions and provides useful guides.",
          learningMode: "understand"
        },
        {
          type: "quiz",
          title: "Knowledge Check",
          content: JSON.stringify({
            question: "What is the key focus of " + input.topic + "?",
            options: ["The target goals", "Irrelevant activities", "Other items"],
            correctAnswer: "The target goals",
            explanation: "The module focuses on attaining the key goals related to the topic."
          }),
          learningMode: "test"
        }
      ]
    };
  }
}
